export const WORKING_LIST_REQUEST = 'WORKING_LIST_REQUEST';
export const WORKING_LIST_SUCCESS = 'WORKING_LIST_SUCCESS';
export const WORKING_LIST_FAIL = 'WORKING_LIST_FAIL';
export const WORKING_LIST_CLEAR = 'WORKING_LIST_CLEAR';
export const WORKING_SET_CURRENT_END = 'WORKING_SET_CURRENT_END';
export const WORKING_SET_CURRENT_NONE = 'WORKING_SET_CURRENT_NONE';
export const WORKING_SET_TOTAL_PAGE = 'WORKING_SET_TOTAL_PAGE';
export const WORKING_SET_CURRENT_PAGE = 'WORKING_SET_CURRENT_PAGE';
export const WORKING_SET_FETCHING = 'WORKING_SET_FETCHING';

export const WORKING_DETAILS_REQUEST = 'WORKING_DETAILS_REQUEST';
export const WORKING_DETAILS_SUCCESS = 'WORKING_DETAILS_SUCCESS';
export const WORKING_DETAILS_FAIL = 'WORKING_DETAILS_FAIL';

export const WORKING_POSITIONS_REQUEST = 'WORKING_DETAILS_REQUEST';
export const WORKING_POSITIONS_SUCCESS = 'WORKING_DETAILS_SUCCESS';
export const WORKING_POSITIONS_FAIL = 'WORKING_DETAILS_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";