export const WORKING_LIST_REQUEST = 'WORKING_LIST_REQUEST';
export const WORKING_LIST_SUCCESS = 'WORKING_LIST_SUCCESS';
export const WORKING_LIST_FAIL = 'WORKING_LIST_FAIL';

export const WORKING_DETAILS_REQUEST = 'WORKING_DETAILS_REQUEST';
export const WORKING_DETAILS_SUCCESS = 'WORKING_DETAILS_SUCCESS';
export const WORKING_DETAILS_FAIL = 'WORKING_DETAILS_FAIL';