const data = {
    workingItem: [
        {
            _id:'1',
            name:'Salvador Stewart Flynn Thomas Salva Salve',
            email:'frontend_develop@gmail.com',
            phone:'+38 (098) 278 44 24',
            position:'Leading specialist of the department of center of center',
            description:'',
            photo:'/img/photo/Salvador.png',
        },
        {
            _id:'2',
            name:'Takamaru Ayako Jurrien',
            email:'Takamuru@gmail.com',
            phone:'+38 (098) 278 90 25',
            position:'Lead Independent Director',
            description:'',
            photo:'/img/photo/Takamaru.png',
        },
        {
            _id:'3',
            name:'Ilya',
            email:'Ilya_founder@gmail.com',
            phone:'+38 (098) 235 44 29',
            position:'Co-Founder and CEO',
            description:'',
            photo:'/img/photo/Ilya.png',
        },
        {
            _id:'4',
            name:'Alexandre',
            email:'Alexandr_develop@gmail.com',
            phone:'+38 (098) 198 44 24',
            position:'Lead Independent Director',
            description:'',
            photo:'/img/photo/Alexandre.png',
        },
        {
            _id:'5',
            name:'Winny',
            email:'Winny_develop@gmail.com',
            phone:'+38 (098) 278 22 88',
            position:'Former Senior Director',
            description:'',
            photo:'/img/photo/Winny.png',
        },
        {
            _id:'6',
            name:'Simon',
            email:'Simon@gmail.com',
            phone:'+38 (098) 278 44 00',
            position:'President of Commerce',
            description:'',
            photo:'/img/photo/Simon.png',
        },
    ],
};
export default data;